/*import dotenv from 'dotenv';
dotenv.config();

import OpenAI from "openai";

const openai = new OpenAI({apiKey: process.env.OPENAI_API_KEY});

export default async function generateEmbeddings(text){

    //generate mock embeddings

    const embeddingLength = 1024;
    const embedding = Array.from({ length: embeddingLength }, ()=>Math.random());
    console.log("Mock embeddings generated for text: ", text.slice(0,50) + "...");

    return embedding;


    //------------------------------

    // Code snippet to create text embeddings via OpenAI 

    // const response = await openai.embeddings.create({
    //     model:'text-embedding-3-small',
    //     input: text,
    //})
    //
    //return response.data[0].embedding;
}*/

// Cohere LLM
//
import dotenv from 'dotenv';
import axios from 'axios';

dotenv.config();

const COHERE_API_KEY = process.env.COHERE_API_KEY;

console.log('Cohere API key loaded successfully');

export default async function generateEmbeddings(text, useMock = false) {
  if (useMock) {
    const embeddingLength = 1024;
    const embedding = Array.from({ length: embeddingLength }, () => Math.random());
    console.log("Mock embeddings generated for text:", text.slice(0, 50) + "...");
    return embedding;
  }

  try {
    console.log("Generating embeddings for text:", text.slice(0, 50) + "...");

    const response = await axios.post(
      'https://api.cohere.ai/embed',
      {
        model: 'embed-english-v3.0', // Use the appropriate embedding model name
        texts: [text],
      },
      {
        headers: {
          Authorization: `Bearer ${COHERE_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    if (response.data && response.data.embeddings && response.data.embeddings.length > 0) {
      const embedding = response.data.embeddings[0];
      console.log("Cohere embeddings generated for text:", text.slice(0, 50) + "...");
      return embedding;
    } else {
      throw new Error("No embeddings generated by Cohere.");
    }
  } catch (error) {
    console.error("Error generating embeddings:", error.response?.data || error.message);
    throw error;
  }
}