/*
import OpenAI from 'openai';
import dotenv from 'dotenv';
dotenv.config();

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY});

export default async function generateAnswerFromContext(question, context){
    const systemPrompt = `
    You are an assistant that answers questions ONLY based on the provided context.
    If the answer is not in the context, say "I do not have enough context`

    const response = await openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
            { role: "system", content: systemPrompt},
            { role: "user", content: `Context:\n${context}\n\nQuestions: ${questions}`},
        ],
        temperature: 0.2,
    })

    return response.choices[0].message.content.trim();
}
*/


// llmService.js
import dotenv from 'dotenv';
import axios from 'axios';
import { CohereClientV2 } from 'cohere-ai';

dotenv.config();

const COHERE_API_KEY = process.env.COHERE_API_KEY;

console.log('Cohere API key loaded successfully');

const cohere = new CohereClientV2({
  token: COHERE_API_KEY,
})

export default async function generateAnswerFromContext(question, context) {
  const systemPrompt = `
    You are an assistant that answers questions ONLY based on the provided context.
    If the answer is not in the context, say "I do not have enough context."
  `;

  const safeContext = context && context.trim().length > 0 ? context : "No context available.";

  try {
    console.log("Generating answer for question:", question);

    const response = await cohere.chat({
      model: 'command-a-03-2025',
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `Question:${question}\nContext: ${safeContext}` },
      ],
    });

    console.log(response);
    const answer = response.message.content[0].text;

    return answer;

    /*const response = await axios.post(
      'https://api.cohere.ai/v2/chat',
      {
        model: 'command-r-08-2024', // Use the chat model
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Question:${question}\nContext: ${safeContext}` },
        ],
        
        max_tokens: 150,
        temperature: 0.2,
      },
      {
        headers: {
          Authorization: `Bearer ${COHERE_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );
    */

    // Chat API uses `output` instead of `generations`
    

    /*if (response.data && response.data.output && response.data.output.length > 0) {
      const answer = response.data.output[0].content.trim();
      console.log("Generated answer:", answer);
      return answer;
    } else {
      throw new Error("No response generated by Cohere Chat API.");
    }
      */
  } catch (error) {
    console.error("Error generating answer from context:", error.response?.data || error.message);
    throw error;
  }
}
