/*
import OpenAI from 'openai';
import dotenv from 'dotenv';
dotenv.config();

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY});

export default async function generateAnswerFromContext(question, context){
    const systemPrompt = `
    You are an assistant that answers questions ONLY based on the provided context.
    If the answer is not in the context, say "I do not have enough context`

    const response = await openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
            { role: "system", content: systemPrompt},
            { role: "user", content: `Context:\n${context}\n\nQuestions: ${questions}`},
        ],
        temperature: 0.2,
    })

    return response.choices[0].message.content.trim();
}
*/


// llmService.js
import dotenv from 'dotenv';
import axios from 'axios';

dotenv.config();

const COHERE_API_KEY = process.env.COHERE_API_KEY;

console.log('Cohere API key loaded successfully');

export default async function generateAnswerFromContext(question, context) {
  const systemPrompt = `
    You are an assistant that answers questions ONLY based on the provided context.
    If the answer is not in the context, say "I do not have enough context."
  `;

  try {
    console.log("Generating answer for question:", question);

    const response = await axios.post(
      'https://api.cohere.ai/generate',
      {
        model: 'embed-english-v3.0', // Use the appropriate model name
        prompt: `${systemPrompt}\n\nContext:\n${context}\n\nQuestion: ${question}`,
        max_tokens: 50,
        temperature: 0.2,
      },
      {
        headers: {
          Authorization: `Bearer ${COHERE_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    if (response.data && response.data.generations && response.data.generations.length > 0) {
      const answer = response.data.generations[0].text.trim();
      console.log("Generated answer:", answer);
      return answer;
    } else {
      throw new Error("No response generated by Cohere.");
    }
  } catch (error) {
    console.error("Error generating answer from context:", error.response?.data || error.message);
    throw error;
  }
}